@echo off
echo Starting BTP Polypharmacy Pipeline...

echo [1/5] Downloading 2023 FAERS JSON Data...
python src\ingestion\download_faers.py

echo [2/5] Loading Data into DuckDB...
python src\ingestion\faers_loader.py

echo [3/5] Cleaning Drugs Data...
python src\preprocessing\clean_drugs.py

echo [4/5] Cleaning Reactions Data...
python src\preprocessing\clean_reactions.py

echo [5/5] Running Polypharmacy Mining Framework (Multi-Gate)...
python src\analytics\polypharmacy_miner.py

echo Pipeline Complete!
